/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedWebinarsIndexRouteImport } from './routes/_authenticated/webinars/index'
import { Route as AuthenticatedVideoLessonsIndexRouteImport } from './routes/_authenticated/video-lessons/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTeachersIndexRouteImport } from './routes/_authenticated/teachers/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSubjectsIndexRouteImport } from './routes/_authenticated/subjects/index'
import { Route as AuthenticatedSubjectClassIndexRouteImport } from './routes/_authenticated/subject-class/index'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated/students/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSchoolsIndexRouteImport } from './routes/_authenticated/schools/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedLessonTopicsIndexRouteImport } from './routes/_authenticated/lesson-topics/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedHeadDirectoratesIndexRouteImport } from './routes/_authenticated/head-directorates/index'
import { Route as AuthenticatedEducationDepartmentsIndexRouteImport } from './routes/_authenticated/education-departments/index'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated/courses/index'
import { Route as AuthenticatedClassesIndexRouteImport } from './routes/_authenticated/classes/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedBooksIndexRouteImport } from './routes/_authenticated/books/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedWebinarsCreateRouteImport } from './routes/_authenticated/webinars/create'
import { Route as AuthenticatedWebinarsWebinarIdRouteImport } from './routes/_authenticated/webinars/$webinarId'
import { Route as AuthenticatedVideoLessonsCreateRouteImport } from './routes/_authenticated/video-lessons/create'
import { Route as AuthenticatedUsersCreateRouteImport } from './routes/_authenticated/users/create'
import { Route as AuthenticatedSubjectsCreateRouteImport } from './routes/_authenticated/subjects/create'
import { Route as AuthenticatedSubjectClassCreateRouteImport } from './routes/_authenticated/subject-class/create'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSchoolsCreateRouteImport } from './routes/_authenticated/schools/create'
import { Route as AuthenticatedRolesCreateRouteImport } from './routes/_authenticated/roles/create'
import { Route as AuthenticatedLessonTopicsCreateRouteImport } from './routes/_authenticated/lesson-topics/create'
import { Route as AuthenticatedHeadDirectoratesCreateRouteImport } from './routes/_authenticated/head-directorates/create'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedEducationDepartmentsCreateRouteImport } from './routes/_authenticated/education-departments/create'
import { Route as AuthenticatedCoursesCreateRouteImport } from './routes/_authenticated/courses/create'
import { Route as AuthenticatedClassesCreateRouteImport } from './routes/_authenticated/classes/create'
import { Route as AuthenticatedBooksCreateRouteImport } from './routes/_authenticated/books/create'
import { Route as AuthenticatedDictionariesRegionsIndexRouteImport } from './routes/_authenticated/dictionaries/regions/index'
import { Route as AuthenticatedDictionariesDistrictsIndexRouteImport } from './routes/_authenticated/dictionaries/districts/index'
import { Route as AuthenticatedDictionariesCitiesIndexRouteImport } from './routes/_authenticated/dictionaries/cities/index'
import { Route as AuthenticatedWebinarsWebinarIdEditRouteImport } from './routes/_authenticated/webinars/$webinarId.edit'
import { Route as AuthenticatedVideoLessonsVideoLessonIdShowRouteImport } from './routes/_authenticated/video-lessons/$videoLessonId.show'
import { Route as AuthenticatedVideoLessonsVideoLessonIdEditRouteImport } from './routes/_authenticated/video-lessons/$videoLessonId.edit'
import { Route as AuthenticatedUsersUserIdEditRouteImport } from './routes/_authenticated/users/$userId.edit'
import { Route as AuthenticatedSubjectsSubjectIdEditRouteImport } from './routes/_authenticated/subjects/$subjectId.edit'
import { Route as AuthenticatedSubjectClassSubjectClassIdEditRouteImport } from './routes/_authenticated/subject-class/$subjectClassId.edit'
import { Route as AuthenticatedSchoolsSchoolIdEditRouteImport } from './routes/_authenticated/schools/$schoolId.edit'
import { Route as AuthenticatedRolesRoleIdEditRouteImport } from './routes/_authenticated/roles/$roleId.edit'
import { Route as AuthenticatedLessonTopicsLessonTopicIdEditRouteImport } from './routes/_authenticated/lesson-topics/$lessonTopicId.edit'
import { Route as AuthenticatedHeadDirectoratesDirectorateIdEditRouteImport } from './routes/_authenticated/head-directorates/$directorateId.edit'
import { Route as AuthenticatedEducationDepartmentsDepartmentIdEditRouteImport } from './routes/_authenticated/education-departments/$departmentId.edit'
import { Route as AuthenticatedDictionariesRegionsCreateRouteImport } from './routes/_authenticated/dictionaries/regions/create'
import { Route as AuthenticatedDictionariesDistrictsCreateRouteImport } from './routes/_authenticated/dictionaries/districts/create'
import { Route as AuthenticatedDictionariesCitiesCreateRouteImport } from './routes/_authenticated/dictionaries/cities/create'
import { Route as AuthenticatedCoursesCourseIdEditRouteImport } from './routes/_authenticated/courses/$courseId/edit'
import { Route as AuthenticatedClassesClassIdEditRouteImport } from './routes/_authenticated/classes/$classId.edit'
import { Route as AuthenticatedBooksBookIdShowRouteImport } from './routes/_authenticated/books/$bookId.show'
import { Route as AuthenticatedBooksBookIdEditRouteImport } from './routes/_authenticated/books/$bookId.edit'
import { Route as AuthenticatedCoursesCourseIdModulesIndexRouteImport } from './routes/_authenticated/courses/$courseId/modules/index'
import { Route as AuthenticatedDictionariesRegionsRegionIdEditRouteImport } from './routes/_authenticated/dictionaries/regions/$regionId.edit'
import { Route as AuthenticatedDictionariesDistrictsDistrictIdEditRouteImport } from './routes/_authenticated/dictionaries/districts/$districtId.edit'
import { Route as AuthenticatedDictionariesCitiesCityIdEditRouteImport } from './routes/_authenticated/dictionaries/cities/$cityId.edit'
import { Route as AuthenticatedCoursesCourseIdModulesCreateRouteImport } from './routes/_authenticated/courses/$courseId/modules/create'
import { Route as AuthenticatedCoursesCourseIdModulesModuleIdEditRouteImport } from './routes/_authenticated/courses/$courseId/modules/$moduleId/edit'
import { Route as AuthenticatedCoursesCourseIdModulesModuleIdLessonsIndexRouteImport } from './routes/_authenticated/courses/$courseId/modules/$moduleId/lessons/index'
import { Route as AuthenticatedCoursesCourseIdModulesModuleIdLessonsCreateRouteImport } from './routes/_authenticated/courses/$courseId/modules/$moduleId/lessons/create'
import { Route as AuthenticatedCoursesCourseIdModulesModuleIdLessonsLessonIdEditRouteImport } from './routes/_authenticated/courses/$courseId/modules/$moduleId/lessons/$lessonId.edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebinarsIndexRoute =
  AuthenticatedWebinarsIndexRouteImport.update({
    id: '/webinars/',
    path: '/webinars/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVideoLessonsIndexRoute =
  AuthenticatedVideoLessonsIndexRouteImport.update({
    id: '/video-lessons/',
    path: '/video-lessons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeachersIndexRoute =
  AuthenticatedTeachersIndexRouteImport.update({
    id: '/teachers/',
    path: '/teachers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubjectsIndexRoute =
  AuthenticatedSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectClassIndexRoute =
  AuthenticatedSubjectClassIndexRouteImport.update({
    id: '/subject-class/',
    path: '/subject-class/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSchoolsIndexRoute =
  AuthenticatedSchoolsIndexRouteImport.update({
    id: '/schools/',
    path: '/schools/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLessonTopicsIndexRoute =
  AuthenticatedLessonTopicsIndexRouteImport.update({
    id: '/lesson-topics/',
    path: '/lesson-topics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHeadDirectoratesIndexRoute =
  AuthenticatedHeadDirectoratesIndexRouteImport.update({
    id: '/head-directorates/',
    path: '/head-directorates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEducationDepartmentsIndexRoute =
  AuthenticatedEducationDepartmentsIndexRouteImport.update({
    id: '/education-departments/',
    path: '/education-departments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesIndexRoute =
  AuthenticatedClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBooksIndexRoute = AuthenticatedBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebinarsCreateRoute =
  AuthenticatedWebinarsCreateRouteImport.update({
    id: '/webinars/create',
    path: '/webinars/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebinarsWebinarIdRoute =
  AuthenticatedWebinarsWebinarIdRouteImport.update({
    id: '/webinars/$webinarId',
    path: '/webinars/$webinarId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVideoLessonsCreateRoute =
  AuthenticatedVideoLessonsCreateRouteImport.update({
    id: '/video-lessons/create',
    path: '/video-lessons/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersCreateRoute =
  AuthenticatedUsersCreateRouteImport.update({
    id: '/users/create',
    path: '/users/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectsCreateRoute =
  AuthenticatedSubjectsCreateRouteImport.update({
    id: '/subjects/create',
    path: '/subjects/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectClassCreateRoute =
  AuthenticatedSubjectClassCreateRouteImport.update({
    id: '/subject-class/create',
    path: '/subject-class/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSchoolsCreateRoute =
  AuthenticatedSchoolsCreateRouteImport.update({
    id: '/schools/create',
    path: '/schools/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesCreateRoute =
  AuthenticatedRolesCreateRouteImport.update({
    id: '/roles/create',
    path: '/roles/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonTopicsCreateRoute =
  AuthenticatedLessonTopicsCreateRouteImport.update({
    id: '/lesson-topics/create',
    path: '/lesson-topics/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHeadDirectoratesCreateRoute =
  AuthenticatedHeadDirectoratesCreateRouteImport.update({
    id: '/head-directorates/create',
    path: '/head-directorates/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEducationDepartmentsCreateRoute =
  AuthenticatedEducationDepartmentsCreateRouteImport.update({
    id: '/education-departments/create',
    path: '/education-departments/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCreateRoute =
  AuthenticatedCoursesCreateRouteImport.update({
    id: '/courses/create',
    path: '/courses/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesCreateRoute =
  AuthenticatedClassesCreateRouteImport.update({
    id: '/classes/create',
    path: '/classes/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBooksCreateRoute =
  AuthenticatedBooksCreateRouteImport.update({
    id: '/books/create',
    path: '/books/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesRegionsIndexRoute =
  AuthenticatedDictionariesRegionsIndexRouteImport.update({
    id: '/dictionaries/regions/',
    path: '/dictionaries/regions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesDistrictsIndexRoute =
  AuthenticatedDictionariesDistrictsIndexRouteImport.update({
    id: '/dictionaries/districts/',
    path: '/dictionaries/districts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesCitiesIndexRoute =
  AuthenticatedDictionariesCitiesIndexRouteImport.update({
    id: '/dictionaries/cities/',
    path: '/dictionaries/cities/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebinarsWebinarIdEditRoute =
  AuthenticatedWebinarsWebinarIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedWebinarsWebinarIdRoute,
  } as any)
const AuthenticatedVideoLessonsVideoLessonIdShowRoute =
  AuthenticatedVideoLessonsVideoLessonIdShowRouteImport.update({
    id: '/video-lessons/$videoLessonId/show',
    path: '/video-lessons/$videoLessonId/show',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVideoLessonsVideoLessonIdEditRoute =
  AuthenticatedVideoLessonsVideoLessonIdEditRouteImport.update({
    id: '/video-lessons/$videoLessonId/edit',
    path: '/video-lessons/$videoLessonId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersUserIdEditRoute =
  AuthenticatedUsersUserIdEditRouteImport.update({
    id: '/users/$userId/edit',
    path: '/users/$userId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectsSubjectIdEditRoute =
  AuthenticatedSubjectsSubjectIdEditRouteImport.update({
    id: '/subjects/$subjectId/edit',
    path: '/subjects/$subjectId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectClassSubjectClassIdEditRoute =
  AuthenticatedSubjectClassSubjectClassIdEditRouteImport.update({
    id: '/subject-class/$subjectClassId/edit',
    path: '/subject-class/$subjectClassId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchoolsSchoolIdEditRoute =
  AuthenticatedSchoolsSchoolIdEditRouteImport.update({
    id: '/schools/$schoolId/edit',
    path: '/schools/$schoolId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesRoleIdEditRoute =
  AuthenticatedRolesRoleIdEditRouteImport.update({
    id: '/roles/$roleId/edit',
    path: '/roles/$roleId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLessonTopicsLessonTopicIdEditRoute =
  AuthenticatedLessonTopicsLessonTopicIdEditRouteImport.update({
    id: '/lesson-topics/$lessonTopicId/edit',
    path: '/lesson-topics/$lessonTopicId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHeadDirectoratesDirectorateIdEditRoute =
  AuthenticatedHeadDirectoratesDirectorateIdEditRouteImport.update({
    id: '/head-directorates/$directorateId/edit',
    path: '/head-directorates/$directorateId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEducationDepartmentsDepartmentIdEditRoute =
  AuthenticatedEducationDepartmentsDepartmentIdEditRouteImport.update({
    id: '/education-departments/$departmentId/edit',
    path: '/education-departments/$departmentId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesRegionsCreateRoute =
  AuthenticatedDictionariesRegionsCreateRouteImport.update({
    id: '/dictionaries/regions/create',
    path: '/dictionaries/regions/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesDistrictsCreateRoute =
  AuthenticatedDictionariesDistrictsCreateRouteImport.update({
    id: '/dictionaries/districts/create',
    path: '/dictionaries/districts/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesCitiesCreateRoute =
  AuthenticatedDictionariesCitiesCreateRouteImport.update({
    id: '/dictionaries/cities/create',
    path: '/dictionaries/cities/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdEditRoute =
  AuthenticatedCoursesCourseIdEditRouteImport.update({
    id: '/courses/$courseId/edit',
    path: '/courses/$courseId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesClassIdEditRoute =
  AuthenticatedClassesClassIdEditRouteImport.update({
    id: '/classes/$classId/edit',
    path: '/classes/$classId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBooksBookIdShowRoute =
  AuthenticatedBooksBookIdShowRouteImport.update({
    id: '/books/$bookId/show',
    path: '/books/$bookId/show',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBooksBookIdEditRoute =
  AuthenticatedBooksBookIdEditRouteImport.update({
    id: '/books/$bookId/edit',
    path: '/books/$bookId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdModulesIndexRoute =
  AuthenticatedCoursesCourseIdModulesIndexRouteImport.update({
    id: '/courses/$courseId/modules/',
    path: '/courses/$courseId/modules/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesRegionsRegionIdEditRoute =
  AuthenticatedDictionariesRegionsRegionIdEditRouteImport.update({
    id: '/dictionaries/regions/$regionId/edit',
    path: '/dictionaries/regions/$regionId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesDistrictsDistrictIdEditRoute =
  AuthenticatedDictionariesDistrictsDistrictIdEditRouteImport.update({
    id: '/dictionaries/districts/$districtId/edit',
    path: '/dictionaries/districts/$districtId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesCitiesCityIdEditRoute =
  AuthenticatedDictionariesCitiesCityIdEditRouteImport.update({
    id: '/dictionaries/cities/$cityId/edit',
    path: '/dictionaries/cities/$cityId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdModulesCreateRoute =
  AuthenticatedCoursesCourseIdModulesCreateRouteImport.update({
    id: '/courses/$courseId/modules/create',
    path: '/courses/$courseId/modules/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdModulesModuleIdEditRoute =
  AuthenticatedCoursesCourseIdModulesModuleIdEditRouteImport.update({
    id: '/courses/$courseId/modules/$moduleId/edit',
    path: '/courses/$courseId/modules/$moduleId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdModulesModuleIdLessonsIndexRoute =
  AuthenticatedCoursesCourseIdModulesModuleIdLessonsIndexRouteImport.update({
    id: '/courses/$courseId/modules/$moduleId/lessons/',
    path: '/courses/$courseId/modules/$moduleId/lessons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdModulesModuleIdLessonsCreateRoute =
  AuthenticatedCoursesCourseIdModulesModuleIdLessonsCreateRouteImport.update({
    id: '/courses/$courseId/modules/$moduleId/lessons/create',
    path: '/courses/$courseId/modules/$moduleId/lessons/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCoursesCourseIdModulesModuleIdLessonsLessonIdEditRoute =
  AuthenticatedCoursesCourseIdModulesModuleIdLessonsLessonIdEditRouteImport.update(
    {
      id: '/courses/$courseId/modules/$moduleId/lessons/$lessonId/edit',
      path: '/courses/$courseId/modules/$moduleId/lessons/$lessonId/edit',
      getParentRoute: () => AuthenticatedRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/books/create': typeof AuthenticatedBooksCreateRoute
  '/classes/create': typeof AuthenticatedClassesCreateRoute
  '/courses/create': typeof AuthenticatedCoursesCreateRoute
  '/education-departments/create': typeof AuthenticatedEducationDepartmentsCreateRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/head-directorates/create': typeof AuthenticatedHeadDirectoratesCreateRoute
  '/lesson-topics/create': typeof AuthenticatedLessonTopicsCreateRoute
  '/roles/create': typeof AuthenticatedRolesCreateRoute
  '/schools/create': typeof AuthenticatedSchoolsCreateRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/subject-class/create': typeof AuthenticatedSubjectClassCreateRoute
  '/subjects/create': typeof AuthenticatedSubjectsCreateRoute
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/video-lessons/create': typeof AuthenticatedVideoLessonsCreateRoute
  '/webinars/$webinarId': typeof AuthenticatedWebinarsWebinarIdRouteWithChildren
  '/webinars/create': typeof AuthenticatedWebinarsCreateRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/books': typeof AuthenticatedBooksIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/education-departments': typeof AuthenticatedEducationDepartmentsIndexRoute
  '/head-directorates': typeof AuthenticatedHeadDirectoratesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/lesson-topics': typeof AuthenticatedLessonTopicsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/schools': typeof AuthenticatedSchoolsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/subject-class': typeof AuthenticatedSubjectClassIndexRoute
  '/subjects': typeof AuthenticatedSubjectsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/teachers': typeof AuthenticatedTeachersIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/video-lessons': typeof AuthenticatedVideoLessonsIndexRoute
  '/webinars': typeof AuthenticatedWebinarsIndexRoute
  '/books/$bookId/edit': typeof AuthenticatedBooksBookIdEditRoute
  '/books/$bookId/show': typeof AuthenticatedBooksBookIdShowRoute
  '/classes/$classId/edit': typeof AuthenticatedClassesClassIdEditRoute
  '/courses/$courseId/edit': typeof AuthenticatedCoursesCourseIdEditRoute
  '/dictionaries/cities/create': typeof AuthenticatedDictionariesCitiesCreateRoute
  '/dictionaries/districts/create': typeof AuthenticatedDictionariesDistrictsCreateRoute
  '/dictionaries/regions/create': typeof AuthenticatedDictionariesRegionsCreateRoute
  '/education-departments/$departmentId/edit': typeof AuthenticatedEducationDepartmentsDepartmentIdEditRoute
  '/head-directorates/$directorateId/edit': typeof AuthenticatedHeadDirectoratesDirectorateIdEditRoute
  '/lesson-topics/$lessonTopicId/edit': typeof AuthenticatedLessonTopicsLessonTopicIdEditRoute
  '/roles/$roleId/edit': typeof AuthenticatedRolesRoleIdEditRoute
  '/schools/$schoolId/edit': typeof AuthenticatedSchoolsSchoolIdEditRoute
  '/subject-class/$subjectClassId/edit': typeof AuthenticatedSubjectClassSubjectClassIdEditRoute
  '/subjects/$subjectId/edit': typeof AuthenticatedSubjectsSubjectIdEditRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/video-lessons/$videoLessonId/edit': typeof AuthenticatedVideoLessonsVideoLessonIdEditRoute
  '/video-lessons/$videoLessonId/show': typeof AuthenticatedVideoLessonsVideoLessonIdShowRoute
  '/webinars/$webinarId/edit': typeof AuthenticatedWebinarsWebinarIdEditRoute
  '/dictionaries/cities': typeof AuthenticatedDictionariesCitiesIndexRoute
  '/dictionaries/districts': typeof AuthenticatedDictionariesDistrictsIndexRoute
  '/dictionaries/regions': typeof AuthenticatedDictionariesRegionsIndexRoute
  '/courses/$courseId/modules/create': typeof AuthenticatedCoursesCourseIdModulesCreateRoute
  '/dictionaries/cities/$cityId/edit': typeof AuthenticatedDictionariesCitiesCityIdEditRoute
  '/dictionaries/districts/$districtId/edit': typeof AuthenticatedDictionariesDistrictsDistrictIdEditRoute
  '/dictionaries/regions/$regionId/edit': typeof AuthenticatedDictionariesRegionsRegionIdEditRoute
  '/courses/$courseId/modules': typeof AuthenticatedCoursesCourseIdModulesIndexRoute
  '/courses/$courseId/modules/$moduleId/edit': typeof AuthenticatedCoursesCourseIdModulesModuleIdEditRoute
  '/courses/$courseId/modules/$moduleId/lessons/create': typeof AuthenticatedCoursesCourseIdModulesModuleIdLessonsCreateRoute
  '/courses/$courseId/modules/$moduleId/lessons': typeof AuthenticatedCoursesCourseIdModulesModuleIdLessonsIndexRoute
  '/courses/$courseId/modules/$moduleId/lessons/$lessonId/edit': typeof AuthenticatedCoursesCourseIdModulesModuleIdLessonsLessonIdEditRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/books/create': typeof AuthenticatedBooksCreateRoute
  '/classes/create': typeof AuthenticatedClassesCreateRoute
  '/courses/create': typeof AuthenticatedCoursesCreateRoute
  '/education-departments/create': typeof AuthenticatedEducationDepartmentsCreateRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/head-directorates/create': typeof AuthenticatedHeadDirectoratesCreateRoute
  '/lesson-topics/create': typeof AuthenticatedLessonTopicsCreateRoute
  '/roles/create': typeof AuthenticatedRolesCreateRoute
  '/schools/create': typeof AuthenticatedSchoolsCreateRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/subject-class/create': typeof AuthenticatedSubjectClassCreateRoute
  '/subjects/create': typeof AuthenticatedSubjectsCreateRoute
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/video-lessons/create': typeof AuthenticatedVideoLessonsCreateRoute
  '/webinars/$webinarId': typeof AuthenticatedWebinarsWebinarIdRouteWithChildren
  '/webinars/create': typeof AuthenticatedWebinarsCreateRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/books': typeof AuthenticatedBooksIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/education-departments': typeof AuthenticatedEducationDepartmentsIndexRoute
  '/head-directorates': typeof AuthenticatedHeadDirectoratesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/lesson-topics': typeof AuthenticatedLessonTopicsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/schools': typeof AuthenticatedSchoolsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/subject-class': typeof AuthenticatedSubjectClassIndexRoute
  '/subjects': typeof AuthenticatedSubjectsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/teachers': typeof AuthenticatedTeachersIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/video-lessons': typeof AuthenticatedVideoLessonsIndexRoute
  '/webinars': typeof AuthenticatedWebinarsIndexRoute
  '/books/$bookId/edit': typeof AuthenticatedBooksBookIdEditRoute
  '/books/$bookId/show': typeof AuthenticatedBooksBookIdShowRoute
  '/classes/$classId/edit': typeof AuthenticatedClassesClassIdEditRoute
  '/courses/$courseId/edit': typeof AuthenticatedCoursesCourseIdEditRoute
  '/dictionaries/cities/create': typeof AuthenticatedDictionariesCitiesCreateRoute
  '/dictionaries/districts/create': typeof AuthenticatedDictionariesDistrictsCreateRoute
  '/dictionaries/regions/create': typeof AuthenticatedDictionariesRegionsCreateRoute
  '/education-departments/$departmentId/edit': typeof AuthenticatedEducationDepartmentsDepartmentIdEditRoute
  '/head-directorates/$directorateId/edit': typeof AuthenticatedHeadDirectoratesDirectorateIdEditRoute
  '/lesson-topics/$lessonTopicId/edit': typeof AuthenticatedLessonTopicsLessonTopicIdEditRoute
  '/roles/$roleId/edit': typeof AuthenticatedRolesRoleIdEditRoute
  '/schools/$schoolId/edit': typeof AuthenticatedSchoolsSchoolIdEditRoute
  '/subject-class/$subjectClassId/edit': typeof AuthenticatedSubjectClassSubjectClassIdEditRoute
  '/subjects/$subjectId/edit': typeof AuthenticatedSubjectsSubjectIdEditRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/video-lessons/$videoLessonId/edit': typeof AuthenticatedVideoLessonsVideoLessonIdEditRoute
  '/video-lessons/$videoLessonId/show': typeof AuthenticatedVideoLessonsVideoLessonIdShowRoute
  '/webinars/$webinarId/edit': typeof AuthenticatedWebinarsWebinarIdEditRoute
  '/dictionaries/cities': typeof AuthenticatedDictionariesCitiesIndexRoute
  '/dictionaries/districts': typeof AuthenticatedDictionariesDistrictsIndexRoute
  '/dictionaries/regions': typeof AuthenticatedDictionariesRegionsIndexRoute
  '/courses/$courseId/modules/create': typeof AuthenticatedCoursesCourseIdModulesCreateRoute
  '/dictionaries/cities/$cityId/edit': typeof AuthenticatedDictionariesCitiesCityIdEditRoute
  '/dictionaries/districts/$districtId/edit': typeof AuthenticatedDictionariesDistrictsDistrictIdEditRoute
  '/dictionaries/regions/$regionId/edit': typeof AuthenticatedDictionariesRegionsRegionIdEditRoute
  '/courses/$courseId/modules': typeof AuthenticatedCoursesCourseIdModulesIndexRoute
  '/courses/$courseId/modules/$moduleId/edit': typeof AuthenticatedCoursesCourseIdModulesModuleIdEditRoute
  '/courses/$courseId/modules/$moduleId/lessons/create': typeof AuthenticatedCoursesCourseIdModulesModuleIdLessonsCreateRoute
  '/courses/$courseId/modules/$moduleId/lessons': typeof AuthenticatedCoursesCourseIdModulesModuleIdLessonsIndexRoute
  '/courses/$courseId/modules/$moduleId/lessons/$lessonId/edit': typeof AuthenticatedCoursesCourseIdModulesModuleIdLessonsLessonIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/books/create': typeof AuthenticatedBooksCreateRoute
  '/_authenticated/classes/create': typeof AuthenticatedClassesCreateRoute
  '/_authenticated/courses/create': typeof AuthenticatedCoursesCreateRoute
  '/_authenticated/education-departments/create': typeof AuthenticatedEducationDepartmentsCreateRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/head-directorates/create': typeof AuthenticatedHeadDirectoratesCreateRoute
  '/_authenticated/lesson-topics/create': typeof AuthenticatedLessonTopicsCreateRoute
  '/_authenticated/roles/create': typeof AuthenticatedRolesCreateRoute
  '/_authenticated/schools/create': typeof AuthenticatedSchoolsCreateRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/subject-class/create': typeof AuthenticatedSubjectClassCreateRoute
  '/_authenticated/subjects/create': typeof AuthenticatedSubjectsCreateRoute
  '/_authenticated/users/create': typeof AuthenticatedUsersCreateRoute
  '/_authenticated/video-lessons/create': typeof AuthenticatedVideoLessonsCreateRoute
  '/_authenticated/webinars/$webinarId': typeof AuthenticatedWebinarsWebinarIdRouteWithChildren
  '/_authenticated/webinars/create': typeof AuthenticatedWebinarsCreateRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/books/': typeof AuthenticatedBooksIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/classes/': typeof AuthenticatedClassesIndexRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
  '/_authenticated/education-departments/': typeof AuthenticatedEducationDepartmentsIndexRoute
  '/_authenticated/head-directorates/': typeof AuthenticatedHeadDirectoratesIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/lesson-topics/': typeof AuthenticatedLessonTopicsIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/schools/': typeof AuthenticatedSchoolsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/subject-class/': typeof AuthenticatedSubjectClassIndexRoute
  '/_authenticated/subjects/': typeof AuthenticatedSubjectsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/video-lessons/': typeof AuthenticatedVideoLessonsIndexRoute
  '/_authenticated/webinars/': typeof AuthenticatedWebinarsIndexRoute
  '/_authenticated/books/$bookId/edit': typeof AuthenticatedBooksBookIdEditRoute
  '/_authenticated/books/$bookId/show': typeof AuthenticatedBooksBookIdShowRoute
  '/_authenticated/classes/$classId/edit': typeof AuthenticatedClassesClassIdEditRoute
  '/_authenticated/courses/$courseId/edit': typeof AuthenticatedCoursesCourseIdEditRoute
  '/_authenticated/dictionaries/cities/create': typeof AuthenticatedDictionariesCitiesCreateRoute
  '/_authenticated/dictionaries/districts/create': typeof AuthenticatedDictionariesDistrictsCreateRoute
  '/_authenticated/dictionaries/regions/create': typeof AuthenticatedDictionariesRegionsCreateRoute
  '/_authenticated/education-departments/$departmentId/edit': typeof AuthenticatedEducationDepartmentsDepartmentIdEditRoute
  '/_authenticated/head-directorates/$directorateId/edit': typeof AuthenticatedHeadDirectoratesDirectorateIdEditRoute
  '/_authenticated/lesson-topics/$lessonTopicId/edit': typeof AuthenticatedLessonTopicsLessonTopicIdEditRoute
  '/_authenticated/roles/$roleId/edit': typeof AuthenticatedRolesRoleIdEditRoute
  '/_authenticated/schools/$schoolId/edit': typeof AuthenticatedSchoolsSchoolIdEditRoute
  '/_authenticated/subject-class/$subjectClassId/edit': typeof AuthenticatedSubjectClassSubjectClassIdEditRoute
  '/_authenticated/subjects/$subjectId/edit': typeof AuthenticatedSubjectsSubjectIdEditRoute
  '/_authenticated/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/_authenticated/video-lessons/$videoLessonId/edit': typeof AuthenticatedVideoLessonsVideoLessonIdEditRoute
  '/_authenticated/video-lessons/$videoLessonId/show': typeof AuthenticatedVideoLessonsVideoLessonIdShowRoute
  '/_authenticated/webinars/$webinarId/edit': typeof AuthenticatedWebinarsWebinarIdEditRoute
  '/_authenticated/dictionaries/cities/': typeof AuthenticatedDictionariesCitiesIndexRoute
  '/_authenticated/dictionaries/districts/': typeof AuthenticatedDictionariesDistrictsIndexRoute
  '/_authenticated/dictionaries/regions/': typeof AuthenticatedDictionariesRegionsIndexRoute
  '/_authenticated/courses/$courseId/modules/create': typeof AuthenticatedCoursesCourseIdModulesCreateRoute
  '/_authenticated/dictionaries/cities/$cityId/edit': typeof AuthenticatedDictionariesCitiesCityIdEditRoute
  '/_authenticated/dictionaries/districts/$districtId/edit': typeof AuthenticatedDictionariesDistrictsDistrictIdEditRoute
  '/_authenticated/dictionaries/regions/$regionId/edit': typeof AuthenticatedDictionariesRegionsRegionIdEditRoute
  '/_authenticated/courses/$courseId/modules/': typeof AuthenticatedCoursesCourseIdModulesIndexRoute
  '/_authenticated/courses/$courseId/modules/$moduleId/edit': typeof AuthenticatedCoursesCourseIdModulesModuleIdEditRoute
  '/_authenticated/courses/$courseId/modules/$moduleId/lessons/create': typeof AuthenticatedCoursesCourseIdModulesModuleIdLessonsCreateRoute
  '/_authenticated/courses/$courseId/modules/$moduleId/lessons/': typeof AuthenticatedCoursesCourseIdModulesModuleIdLessonsIndexRoute
  '/_authenticated/courses/$courseId/modules/$moduleId/lessons/$lessonId/edit': typeof AuthenticatedCoursesCourseIdModulesModuleIdLessonsLessonIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/books/create'
    | '/classes/create'
    | '/courses/create'
    | '/education-departments/create'
    | '/errors/$error'
    | '/head-directorates/create'
    | '/lesson-topics/create'
    | '/roles/create'
    | '/schools/create'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/subject-class/create'
    | '/subjects/create'
    | '/users/create'
    | '/video-lessons/create'
    | '/webinars/$webinarId'
    | '/webinars/create'
    | '/apps'
    | '/books'
    | '/chats'
    | '/classes'
    | '/courses'
    | '/education-departments'
    | '/head-directorates'
    | '/help-center'
    | '/lesson-topics'
    | '/roles'
    | '/schools'
    | '/settings/'
    | '/students'
    | '/subject-class'
    | '/subjects'
    | '/tasks'
    | '/teachers'
    | '/users'
    | '/video-lessons'
    | '/webinars'
    | '/books/$bookId/edit'
    | '/books/$bookId/show'
    | '/classes/$classId/edit'
    | '/courses/$courseId/edit'
    | '/dictionaries/cities/create'
    | '/dictionaries/districts/create'
    | '/dictionaries/regions/create'
    | '/education-departments/$departmentId/edit'
    | '/head-directorates/$directorateId/edit'
    | '/lesson-topics/$lessonTopicId/edit'
    | '/roles/$roleId/edit'
    | '/schools/$schoolId/edit'
    | '/subject-class/$subjectClassId/edit'
    | '/subjects/$subjectId/edit'
    | '/users/$userId/edit'
    | '/video-lessons/$videoLessonId/edit'
    | '/video-lessons/$videoLessonId/show'
    | '/webinars/$webinarId/edit'
    | '/dictionaries/cities'
    | '/dictionaries/districts'
    | '/dictionaries/regions'
    | '/courses/$courseId/modules/create'
    | '/dictionaries/cities/$cityId/edit'
    | '/dictionaries/districts/$districtId/edit'
    | '/dictionaries/regions/$regionId/edit'
    | '/courses/$courseId/modules'
    | '/courses/$courseId/modules/$moduleId/edit'
    | '/courses/$courseId/modules/$moduleId/lessons/create'
    | '/courses/$courseId/modules/$moduleId/lessons'
    | '/courses/$courseId/modules/$moduleId/lessons/$lessonId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/books/create'
    | '/classes/create'
    | '/courses/create'
    | '/education-departments/create'
    | '/errors/$error'
    | '/head-directorates/create'
    | '/lesson-topics/create'
    | '/roles/create'
    | '/schools/create'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/subject-class/create'
    | '/subjects/create'
    | '/users/create'
    | '/video-lessons/create'
    | '/webinars/$webinarId'
    | '/webinars/create'
    | '/apps'
    | '/books'
    | '/chats'
    | '/classes'
    | '/courses'
    | '/education-departments'
    | '/head-directorates'
    | '/help-center'
    | '/lesson-topics'
    | '/roles'
    | '/schools'
    | '/settings'
    | '/students'
    | '/subject-class'
    | '/subjects'
    | '/tasks'
    | '/teachers'
    | '/users'
    | '/video-lessons'
    | '/webinars'
    | '/books/$bookId/edit'
    | '/books/$bookId/show'
    | '/classes/$classId/edit'
    | '/courses/$courseId/edit'
    | '/dictionaries/cities/create'
    | '/dictionaries/districts/create'
    | '/dictionaries/regions/create'
    | '/education-departments/$departmentId/edit'
    | '/head-directorates/$directorateId/edit'
    | '/lesson-topics/$lessonTopicId/edit'
    | '/roles/$roleId/edit'
    | '/schools/$schoolId/edit'
    | '/subject-class/$subjectClassId/edit'
    | '/subjects/$subjectId/edit'
    | '/users/$userId/edit'
    | '/video-lessons/$videoLessonId/edit'
    | '/video-lessons/$videoLessonId/show'
    | '/webinars/$webinarId/edit'
    | '/dictionaries/cities'
    | '/dictionaries/districts'
    | '/dictionaries/regions'
    | '/courses/$courseId/modules/create'
    | '/dictionaries/cities/$cityId/edit'
    | '/dictionaries/districts/$districtId/edit'
    | '/dictionaries/regions/$regionId/edit'
    | '/courses/$courseId/modules'
    | '/courses/$courseId/modules/$moduleId/edit'
    | '/courses/$courseId/modules/$moduleId/lessons/create'
    | '/courses/$courseId/modules/$moduleId/lessons'
    | '/courses/$courseId/modules/$moduleId/lessons/$lessonId/edit'
  id:
    | '__root__'
    | '/(auth)'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/books/create'
    | '/_authenticated/classes/create'
    | '/_authenticated/courses/create'
    | '/_authenticated/education-departments/create'
    | '/_authenticated/errors/$error'
    | '/_authenticated/head-directorates/create'
    | '/_authenticated/lesson-topics/create'
    | '/_authenticated/roles/create'
    | '/_authenticated/schools/create'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/subject-class/create'
    | '/_authenticated/subjects/create'
    | '/_authenticated/users/create'
    | '/_authenticated/video-lessons/create'
    | '/_authenticated/webinars/$webinarId'
    | '/_authenticated/webinars/create'
    | '/_authenticated/apps/'
    | '/_authenticated/books/'
    | '/_authenticated/chats/'
    | '/_authenticated/classes/'
    | '/_authenticated/courses/'
    | '/_authenticated/education-departments/'
    | '/_authenticated/head-directorates/'
    | '/_authenticated/help-center/'
    | '/_authenticated/lesson-topics/'
    | '/_authenticated/roles/'
    | '/_authenticated/schools/'
    | '/_authenticated/settings/'
    | '/_authenticated/students/'
    | '/_authenticated/subject-class/'
    | '/_authenticated/subjects/'
    | '/_authenticated/tasks/'
    | '/_authenticated/teachers/'
    | '/_authenticated/users/'
    | '/_authenticated/video-lessons/'
    | '/_authenticated/webinars/'
    | '/_authenticated/books/$bookId/edit'
    | '/_authenticated/books/$bookId/show'
    | '/_authenticated/classes/$classId/edit'
    | '/_authenticated/courses/$courseId/edit'
    | '/_authenticated/dictionaries/cities/create'
    | '/_authenticated/dictionaries/districts/create'
    | '/_authenticated/dictionaries/regions/create'
    | '/_authenticated/education-departments/$departmentId/edit'
    | '/_authenticated/head-directorates/$directorateId/edit'
    | '/_authenticated/lesson-topics/$lessonTopicId/edit'
    | '/_authenticated/roles/$roleId/edit'
    | '/_authenticated/schools/$schoolId/edit'
    | '/_authenticated/subject-class/$subjectClassId/edit'
    | '/_authenticated/subjects/$subjectId/edit'
    | '/_authenticated/users/$userId/edit'
    | '/_authenticated/video-lessons/$videoLessonId/edit'
    | '/_authenticated/video-lessons/$videoLessonId/show'
    | '/_authenticated/webinars/$webinarId/edit'
    | '/_authenticated/dictionaries/cities/'
    | '/_authenticated/dictionaries/districts/'
    | '/_authenticated/dictionaries/regions/'
    | '/_authenticated/courses/$courseId/modules/create'
    | '/_authenticated/dictionaries/cities/$cityId/edit'
    | '/_authenticated/dictionaries/districts/$districtId/edit'
    | '/_authenticated/dictionaries/regions/$regionId/edit'
    | '/_authenticated/courses/$courseId/modules/'
    | '/_authenticated/courses/$courseId/modules/$moduleId/edit'
    | '/_authenticated/courses/$courseId/modules/$moduleId/lessons/create'
    | '/_authenticated/courses/$courseId/modules/$moduleId/lessons/'
    | '/_authenticated/courses/$courseId/modules/$moduleId/lessons/$lessonId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webinars/': {
      id: '/_authenticated/webinars/'
      path: '/webinars'
      fullPath: '/webinars'
      preLoaderRoute: typeof AuthenticatedWebinarsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/video-lessons/': {
      id: '/_authenticated/video-lessons/'
      path: '/video-lessons'
      fullPath: '/video-lessons'
      preLoaderRoute: typeof AuthenticatedVideoLessonsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teachers/': {
      id: '/_authenticated/teachers/'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AuthenticatedTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/': {
      id: '/_authenticated/subjects/'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AuthenticatedSubjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subject-class/': {
      id: '/_authenticated/subject-class/'
      path: '/subject-class'
      fullPath: '/subject-class'
      preLoaderRoute: typeof AuthenticatedSubjectClassIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/schools/': {
      id: '/_authenticated/schools/'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof AuthenticatedSchoolsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lesson-topics/': {
      id: '/_authenticated/lesson-topics/'
      path: '/lesson-topics'
      fullPath: '/lesson-topics'
      preLoaderRoute: typeof AuthenticatedLessonTopicsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/head-directorates/': {
      id: '/_authenticated/head-directorates/'
      path: '/head-directorates'
      fullPath: '/head-directorates'
      preLoaderRoute: typeof AuthenticatedHeadDirectoratesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/education-departments/': {
      id: '/_authenticated/education-departments/'
      path: '/education-departments'
      fullPath: '/education-departments'
      preLoaderRoute: typeof AuthenticatedEducationDepartmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/': {
      id: '/_authenticated/classes/'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/': {
      id: '/_authenticated/books/'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof AuthenticatedBooksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webinars/create': {
      id: '/_authenticated/webinars/create'
      path: '/webinars/create'
      fullPath: '/webinars/create'
      preLoaderRoute: typeof AuthenticatedWebinarsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webinars/$webinarId': {
      id: '/_authenticated/webinars/$webinarId'
      path: '/webinars/$webinarId'
      fullPath: '/webinars/$webinarId'
      preLoaderRoute: typeof AuthenticatedWebinarsWebinarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/video-lessons/create': {
      id: '/_authenticated/video-lessons/create'
      path: '/video-lessons/create'
      fullPath: '/video-lessons/create'
      preLoaderRoute: typeof AuthenticatedVideoLessonsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/create': {
      id: '/_authenticated/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AuthenticatedUsersCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/create': {
      id: '/_authenticated/subjects/create'
      path: '/subjects/create'
      fullPath: '/subjects/create'
      preLoaderRoute: typeof AuthenticatedSubjectsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subject-class/create': {
      id: '/_authenticated/subject-class/create'
      path: '/subject-class/create'
      fullPath: '/subject-class/create'
      preLoaderRoute: typeof AuthenticatedSubjectClassCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/schools/create': {
      id: '/_authenticated/schools/create'
      path: '/schools/create'
      fullPath: '/schools/create'
      preLoaderRoute: typeof AuthenticatedSchoolsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/create': {
      id: '/_authenticated/roles/create'
      path: '/roles/create'
      fullPath: '/roles/create'
      preLoaderRoute: typeof AuthenticatedRolesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lesson-topics/create': {
      id: '/_authenticated/lesson-topics/create'
      path: '/lesson-topics/create'
      fullPath: '/lesson-topics/create'
      preLoaderRoute: typeof AuthenticatedLessonTopicsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/head-directorates/create': {
      id: '/_authenticated/head-directorates/create'
      path: '/head-directorates/create'
      fullPath: '/head-directorates/create'
      preLoaderRoute: typeof AuthenticatedHeadDirectoratesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/education-departments/create': {
      id: '/_authenticated/education-departments/create'
      path: '/education-departments/create'
      fullPath: '/education-departments/create'
      preLoaderRoute: typeof AuthenticatedEducationDepartmentsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/create': {
      id: '/_authenticated/courses/create'
      path: '/courses/create'
      fullPath: '/courses/create'
      preLoaderRoute: typeof AuthenticatedCoursesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/create': {
      id: '/_authenticated/classes/create'
      path: '/classes/create'
      fullPath: '/classes/create'
      preLoaderRoute: typeof AuthenticatedClassesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/create': {
      id: '/_authenticated/books/create'
      path: '/books/create'
      fullPath: '/books/create'
      preLoaderRoute: typeof AuthenticatedBooksCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/regions/': {
      id: '/_authenticated/dictionaries/regions/'
      path: '/dictionaries/regions'
      fullPath: '/dictionaries/regions'
      preLoaderRoute: typeof AuthenticatedDictionariesRegionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/districts/': {
      id: '/_authenticated/dictionaries/districts/'
      path: '/dictionaries/districts'
      fullPath: '/dictionaries/districts'
      preLoaderRoute: typeof AuthenticatedDictionariesDistrictsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/cities/': {
      id: '/_authenticated/dictionaries/cities/'
      path: '/dictionaries/cities'
      fullPath: '/dictionaries/cities'
      preLoaderRoute: typeof AuthenticatedDictionariesCitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webinars/$webinarId/edit': {
      id: '/_authenticated/webinars/$webinarId/edit'
      path: '/edit'
      fullPath: '/webinars/$webinarId/edit'
      preLoaderRoute: typeof AuthenticatedWebinarsWebinarIdEditRouteImport
      parentRoute: typeof AuthenticatedWebinarsWebinarIdRoute
    }
    '/_authenticated/video-lessons/$videoLessonId/show': {
      id: '/_authenticated/video-lessons/$videoLessonId/show'
      path: '/video-lessons/$videoLessonId/show'
      fullPath: '/video-lessons/$videoLessonId/show'
      preLoaderRoute: typeof AuthenticatedVideoLessonsVideoLessonIdShowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/video-lessons/$videoLessonId/edit': {
      id: '/_authenticated/video-lessons/$videoLessonId/edit'
      path: '/video-lessons/$videoLessonId/edit'
      fullPath: '/video-lessons/$videoLessonId/edit'
      preLoaderRoute: typeof AuthenticatedVideoLessonsVideoLessonIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$userId/edit': {
      id: '/_authenticated/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof AuthenticatedUsersUserIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/$subjectId/edit': {
      id: '/_authenticated/subjects/$subjectId/edit'
      path: '/subjects/$subjectId/edit'
      fullPath: '/subjects/$subjectId/edit'
      preLoaderRoute: typeof AuthenticatedSubjectsSubjectIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subject-class/$subjectClassId/edit': {
      id: '/_authenticated/subject-class/$subjectClassId/edit'
      path: '/subject-class/$subjectClassId/edit'
      fullPath: '/subject-class/$subjectClassId/edit'
      preLoaderRoute: typeof AuthenticatedSubjectClassSubjectClassIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schools/$schoolId/edit': {
      id: '/_authenticated/schools/$schoolId/edit'
      path: '/schools/$schoolId/edit'
      fullPath: '/schools/$schoolId/edit'
      preLoaderRoute: typeof AuthenticatedSchoolsSchoolIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/$roleId/edit': {
      id: '/_authenticated/roles/$roleId/edit'
      path: '/roles/$roleId/edit'
      fullPath: '/roles/$roleId/edit'
      preLoaderRoute: typeof AuthenticatedRolesRoleIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lesson-topics/$lessonTopicId/edit': {
      id: '/_authenticated/lesson-topics/$lessonTopicId/edit'
      path: '/lesson-topics/$lessonTopicId/edit'
      fullPath: '/lesson-topics/$lessonTopicId/edit'
      preLoaderRoute: typeof AuthenticatedLessonTopicsLessonTopicIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/head-directorates/$directorateId/edit': {
      id: '/_authenticated/head-directorates/$directorateId/edit'
      path: '/head-directorates/$directorateId/edit'
      fullPath: '/head-directorates/$directorateId/edit'
      preLoaderRoute: typeof AuthenticatedHeadDirectoratesDirectorateIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/education-departments/$departmentId/edit': {
      id: '/_authenticated/education-departments/$departmentId/edit'
      path: '/education-departments/$departmentId/edit'
      fullPath: '/education-departments/$departmentId/edit'
      preLoaderRoute: typeof AuthenticatedEducationDepartmentsDepartmentIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/regions/create': {
      id: '/_authenticated/dictionaries/regions/create'
      path: '/dictionaries/regions/create'
      fullPath: '/dictionaries/regions/create'
      preLoaderRoute: typeof AuthenticatedDictionariesRegionsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/districts/create': {
      id: '/_authenticated/dictionaries/districts/create'
      path: '/dictionaries/districts/create'
      fullPath: '/dictionaries/districts/create'
      preLoaderRoute: typeof AuthenticatedDictionariesDistrictsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/cities/create': {
      id: '/_authenticated/dictionaries/cities/create'
      path: '/dictionaries/cities/create'
      fullPath: '/dictionaries/cities/create'
      preLoaderRoute: typeof AuthenticatedDictionariesCitiesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$courseId/edit': {
      id: '/_authenticated/courses/$courseId/edit'
      path: '/courses/$courseId/edit'
      fullPath: '/courses/$courseId/edit'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/$classId/edit': {
      id: '/_authenticated/classes/$classId/edit'
      path: '/classes/$classId/edit'
      fullPath: '/classes/$classId/edit'
      preLoaderRoute: typeof AuthenticatedClassesClassIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/$bookId/show': {
      id: '/_authenticated/books/$bookId/show'
      path: '/books/$bookId/show'
      fullPath: '/books/$bookId/show'
      preLoaderRoute: typeof AuthenticatedBooksBookIdShowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/books/$bookId/edit': {
      id: '/_authenticated/books/$bookId/edit'
      path: '/books/$bookId/edit'
      fullPath: '/books/$bookId/edit'
      preLoaderRoute: typeof AuthenticatedBooksBookIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$courseId/modules/': {
      id: '/_authenticated/courses/$courseId/modules/'
      path: '/courses/$courseId/modules'
      fullPath: '/courses/$courseId/modules'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdModulesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/regions/$regionId/edit': {
      id: '/_authenticated/dictionaries/regions/$regionId/edit'
      path: '/dictionaries/regions/$regionId/edit'
      fullPath: '/dictionaries/regions/$regionId/edit'
      preLoaderRoute: typeof AuthenticatedDictionariesRegionsRegionIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/districts/$districtId/edit': {
      id: '/_authenticated/dictionaries/districts/$districtId/edit'
      path: '/dictionaries/districts/$districtId/edit'
      fullPath: '/dictionaries/districts/$districtId/edit'
      preLoaderRoute: typeof AuthenticatedDictionariesDistrictsDistrictIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/cities/$cityId/edit': {
      id: '/_authenticated/dictionaries/cities/$cityId/edit'
      path: '/dictionaries/cities/$cityId/edit'
      fullPath: '/dictionaries/cities/$cityId/edit'
      preLoaderRoute: typeof AuthenticatedDictionariesCitiesCityIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$courseId/modules/create': {
      id: '/_authenticated/courses/$courseId/modules/create'
      path: '/courses/$courseId/modules/create'
      fullPath: '/courses/$courseId/modules/create'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdModulesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$courseId/modules/$moduleId/edit': {
      id: '/_authenticated/courses/$courseId/modules/$moduleId/edit'
      path: '/courses/$courseId/modules/$moduleId/edit'
      fullPath: '/courses/$courseId/modules/$moduleId/edit'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdModulesModuleIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$courseId/modules/$moduleId/lessons/': {
      id: '/_authenticated/courses/$courseId/modules/$moduleId/lessons/'
      path: '/courses/$courseId/modules/$moduleId/lessons'
      fullPath: '/courses/$courseId/modules/$moduleId/lessons'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdModulesModuleIdLessonsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$courseId/modules/$moduleId/lessons/create': {
      id: '/_authenticated/courses/$courseId/modules/$moduleId/lessons/create'
      path: '/courses/$courseId/modules/$moduleId/lessons/create'
      fullPath: '/courses/$courseId/modules/$moduleId/lessons/create'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdModulesModuleIdLessonsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/courses/$courseId/modules/$moduleId/lessons/$lessonId/edit': {
      id: '/_authenticated/courses/$courseId/modules/$moduleId/lessons/$lessonId/edit'
      path: '/courses/$courseId/modules/$moduleId/lessons/$lessonId/edit'
      fullPath: '/courses/$courseId/modules/$moduleId/lessons/$lessonId/edit'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdModulesModuleIdLessonsLessonIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedWebinarsWebinarIdRouteChildren {
  AuthenticatedWebinarsWebinarIdEditRoute: typeof AuthenticatedWebinarsWebinarIdEditRoute
}

const AuthenticatedWebinarsWebinarIdRouteChildren: AuthenticatedWebinarsWebinarIdRouteChildren =
  {
    AuthenticatedWebinarsWebinarIdEditRoute:
      AuthenticatedWebinarsWebinarIdEditRoute,
  }

const AuthenticatedWebinarsWebinarIdRouteWithChildren =
  AuthenticatedWebinarsWebinarIdRoute._addFileChildren(
    AuthenticatedWebinarsWebinarIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBooksCreateRoute: typeof AuthenticatedBooksCreateRoute
  AuthenticatedClassesCreateRoute: typeof AuthenticatedClassesCreateRoute
  AuthenticatedCoursesCreateRoute: typeof AuthenticatedCoursesCreateRoute
  AuthenticatedEducationDepartmentsCreateRoute: typeof AuthenticatedEducationDepartmentsCreateRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedHeadDirectoratesCreateRoute: typeof AuthenticatedHeadDirectoratesCreateRoute
  AuthenticatedLessonTopicsCreateRoute: typeof AuthenticatedLessonTopicsCreateRoute
  AuthenticatedRolesCreateRoute: typeof AuthenticatedRolesCreateRoute
  AuthenticatedSchoolsCreateRoute: typeof AuthenticatedSchoolsCreateRoute
  AuthenticatedSubjectClassCreateRoute: typeof AuthenticatedSubjectClassCreateRoute
  AuthenticatedSubjectsCreateRoute: typeof AuthenticatedSubjectsCreateRoute
  AuthenticatedUsersCreateRoute: typeof AuthenticatedUsersCreateRoute
  AuthenticatedVideoLessonsCreateRoute: typeof AuthenticatedVideoLessonsCreateRoute
  AuthenticatedWebinarsWebinarIdRoute: typeof AuthenticatedWebinarsWebinarIdRouteWithChildren
  AuthenticatedWebinarsCreateRoute: typeof AuthenticatedWebinarsCreateRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedBooksIndexRoute: typeof AuthenticatedBooksIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedClassesIndexRoute: typeof AuthenticatedClassesIndexRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
  AuthenticatedEducationDepartmentsIndexRoute: typeof AuthenticatedEducationDepartmentsIndexRoute
  AuthenticatedHeadDirectoratesIndexRoute: typeof AuthenticatedHeadDirectoratesIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedLessonTopicsIndexRoute: typeof AuthenticatedLessonTopicsIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedSchoolsIndexRoute: typeof AuthenticatedSchoolsIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedSubjectClassIndexRoute: typeof AuthenticatedSubjectClassIndexRoute
  AuthenticatedSubjectsIndexRoute: typeof AuthenticatedSubjectsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTeachersIndexRoute: typeof AuthenticatedTeachersIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedVideoLessonsIndexRoute: typeof AuthenticatedVideoLessonsIndexRoute
  AuthenticatedWebinarsIndexRoute: typeof AuthenticatedWebinarsIndexRoute
  AuthenticatedBooksBookIdEditRoute: typeof AuthenticatedBooksBookIdEditRoute
  AuthenticatedBooksBookIdShowRoute: typeof AuthenticatedBooksBookIdShowRoute
  AuthenticatedClassesClassIdEditRoute: typeof AuthenticatedClassesClassIdEditRoute
  AuthenticatedCoursesCourseIdEditRoute: typeof AuthenticatedCoursesCourseIdEditRoute
  AuthenticatedDictionariesCitiesCreateRoute: typeof AuthenticatedDictionariesCitiesCreateRoute
  AuthenticatedDictionariesDistrictsCreateRoute: typeof AuthenticatedDictionariesDistrictsCreateRoute
  AuthenticatedDictionariesRegionsCreateRoute: typeof AuthenticatedDictionariesRegionsCreateRoute
  AuthenticatedEducationDepartmentsDepartmentIdEditRoute: typeof AuthenticatedEducationDepartmentsDepartmentIdEditRoute
  AuthenticatedHeadDirectoratesDirectorateIdEditRoute: typeof AuthenticatedHeadDirectoratesDirectorateIdEditRoute
  AuthenticatedLessonTopicsLessonTopicIdEditRoute: typeof AuthenticatedLessonTopicsLessonTopicIdEditRoute
  AuthenticatedRolesRoleIdEditRoute: typeof AuthenticatedRolesRoleIdEditRoute
  AuthenticatedSchoolsSchoolIdEditRoute: typeof AuthenticatedSchoolsSchoolIdEditRoute
  AuthenticatedSubjectClassSubjectClassIdEditRoute: typeof AuthenticatedSubjectClassSubjectClassIdEditRoute
  AuthenticatedSubjectsSubjectIdEditRoute: typeof AuthenticatedSubjectsSubjectIdEditRoute
  AuthenticatedUsersUserIdEditRoute: typeof AuthenticatedUsersUserIdEditRoute
  AuthenticatedVideoLessonsVideoLessonIdEditRoute: typeof AuthenticatedVideoLessonsVideoLessonIdEditRoute
  AuthenticatedVideoLessonsVideoLessonIdShowRoute: typeof AuthenticatedVideoLessonsVideoLessonIdShowRoute
  AuthenticatedDictionariesCitiesIndexRoute: typeof AuthenticatedDictionariesCitiesIndexRoute
  AuthenticatedDictionariesDistrictsIndexRoute: typeof AuthenticatedDictionariesDistrictsIndexRoute
  AuthenticatedDictionariesRegionsIndexRoute: typeof AuthenticatedDictionariesRegionsIndexRoute
  AuthenticatedCoursesCourseIdModulesCreateRoute: typeof AuthenticatedCoursesCourseIdModulesCreateRoute
  AuthenticatedDictionariesCitiesCityIdEditRoute: typeof AuthenticatedDictionariesCitiesCityIdEditRoute
  AuthenticatedDictionariesDistrictsDistrictIdEditRoute: typeof AuthenticatedDictionariesDistrictsDistrictIdEditRoute
  AuthenticatedDictionariesRegionsRegionIdEditRoute: typeof AuthenticatedDictionariesRegionsRegionIdEditRoute
  AuthenticatedCoursesCourseIdModulesIndexRoute: typeof AuthenticatedCoursesCourseIdModulesIndexRoute
  AuthenticatedCoursesCourseIdModulesModuleIdEditRoute: typeof AuthenticatedCoursesCourseIdModulesModuleIdEditRoute
  AuthenticatedCoursesCourseIdModulesModuleIdLessonsCreateRoute: typeof AuthenticatedCoursesCourseIdModulesModuleIdLessonsCreateRoute
  AuthenticatedCoursesCourseIdModulesModuleIdLessonsIndexRoute: typeof AuthenticatedCoursesCourseIdModulesModuleIdLessonsIndexRoute
  AuthenticatedCoursesCourseIdModulesModuleIdLessonsLessonIdEditRoute: typeof AuthenticatedCoursesCourseIdModulesModuleIdLessonsLessonIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBooksCreateRoute: AuthenticatedBooksCreateRoute,
  AuthenticatedClassesCreateRoute: AuthenticatedClassesCreateRoute,
  AuthenticatedCoursesCreateRoute: AuthenticatedCoursesCreateRoute,
  AuthenticatedEducationDepartmentsCreateRoute:
    AuthenticatedEducationDepartmentsCreateRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedHeadDirectoratesCreateRoute:
    AuthenticatedHeadDirectoratesCreateRoute,
  AuthenticatedLessonTopicsCreateRoute: AuthenticatedLessonTopicsCreateRoute,
  AuthenticatedRolesCreateRoute: AuthenticatedRolesCreateRoute,
  AuthenticatedSchoolsCreateRoute: AuthenticatedSchoolsCreateRoute,
  AuthenticatedSubjectClassCreateRoute: AuthenticatedSubjectClassCreateRoute,
  AuthenticatedSubjectsCreateRoute: AuthenticatedSubjectsCreateRoute,
  AuthenticatedUsersCreateRoute: AuthenticatedUsersCreateRoute,
  AuthenticatedVideoLessonsCreateRoute: AuthenticatedVideoLessonsCreateRoute,
  AuthenticatedWebinarsWebinarIdRoute:
    AuthenticatedWebinarsWebinarIdRouteWithChildren,
  AuthenticatedWebinarsCreateRoute: AuthenticatedWebinarsCreateRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedBooksIndexRoute: AuthenticatedBooksIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedClassesIndexRoute: AuthenticatedClassesIndexRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
  AuthenticatedEducationDepartmentsIndexRoute:
    AuthenticatedEducationDepartmentsIndexRoute,
  AuthenticatedHeadDirectoratesIndexRoute:
    AuthenticatedHeadDirectoratesIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedLessonTopicsIndexRoute: AuthenticatedLessonTopicsIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedSchoolsIndexRoute: AuthenticatedSchoolsIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedSubjectClassIndexRoute: AuthenticatedSubjectClassIndexRoute,
  AuthenticatedSubjectsIndexRoute: AuthenticatedSubjectsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTeachersIndexRoute: AuthenticatedTeachersIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedVideoLessonsIndexRoute: AuthenticatedVideoLessonsIndexRoute,
  AuthenticatedWebinarsIndexRoute: AuthenticatedWebinarsIndexRoute,
  AuthenticatedBooksBookIdEditRoute: AuthenticatedBooksBookIdEditRoute,
  AuthenticatedBooksBookIdShowRoute: AuthenticatedBooksBookIdShowRoute,
  AuthenticatedClassesClassIdEditRoute: AuthenticatedClassesClassIdEditRoute,
  AuthenticatedCoursesCourseIdEditRoute: AuthenticatedCoursesCourseIdEditRoute,
  AuthenticatedDictionariesCitiesCreateRoute:
    AuthenticatedDictionariesCitiesCreateRoute,
  AuthenticatedDictionariesDistrictsCreateRoute:
    AuthenticatedDictionariesDistrictsCreateRoute,
  AuthenticatedDictionariesRegionsCreateRoute:
    AuthenticatedDictionariesRegionsCreateRoute,
  AuthenticatedEducationDepartmentsDepartmentIdEditRoute:
    AuthenticatedEducationDepartmentsDepartmentIdEditRoute,
  AuthenticatedHeadDirectoratesDirectorateIdEditRoute:
    AuthenticatedHeadDirectoratesDirectorateIdEditRoute,
  AuthenticatedLessonTopicsLessonTopicIdEditRoute:
    AuthenticatedLessonTopicsLessonTopicIdEditRoute,
  AuthenticatedRolesRoleIdEditRoute: AuthenticatedRolesRoleIdEditRoute,
  AuthenticatedSchoolsSchoolIdEditRoute: AuthenticatedSchoolsSchoolIdEditRoute,
  AuthenticatedSubjectClassSubjectClassIdEditRoute:
    AuthenticatedSubjectClassSubjectClassIdEditRoute,
  AuthenticatedSubjectsSubjectIdEditRoute:
    AuthenticatedSubjectsSubjectIdEditRoute,
  AuthenticatedUsersUserIdEditRoute: AuthenticatedUsersUserIdEditRoute,
  AuthenticatedVideoLessonsVideoLessonIdEditRoute:
    AuthenticatedVideoLessonsVideoLessonIdEditRoute,
  AuthenticatedVideoLessonsVideoLessonIdShowRoute:
    AuthenticatedVideoLessonsVideoLessonIdShowRoute,
  AuthenticatedDictionariesCitiesIndexRoute:
    AuthenticatedDictionariesCitiesIndexRoute,
  AuthenticatedDictionariesDistrictsIndexRoute:
    AuthenticatedDictionariesDistrictsIndexRoute,
  AuthenticatedDictionariesRegionsIndexRoute:
    AuthenticatedDictionariesRegionsIndexRoute,
  AuthenticatedCoursesCourseIdModulesCreateRoute:
    AuthenticatedCoursesCourseIdModulesCreateRoute,
  AuthenticatedDictionariesCitiesCityIdEditRoute:
    AuthenticatedDictionariesCitiesCityIdEditRoute,
  AuthenticatedDictionariesDistrictsDistrictIdEditRoute:
    AuthenticatedDictionariesDistrictsDistrictIdEditRoute,
  AuthenticatedDictionariesRegionsRegionIdEditRoute:
    AuthenticatedDictionariesRegionsRegionIdEditRoute,
  AuthenticatedCoursesCourseIdModulesIndexRoute:
    AuthenticatedCoursesCourseIdModulesIndexRoute,
  AuthenticatedCoursesCourseIdModulesModuleIdEditRoute:
    AuthenticatedCoursesCourseIdModulesModuleIdEditRoute,
  AuthenticatedCoursesCourseIdModulesModuleIdLessonsCreateRoute:
    AuthenticatedCoursesCourseIdModulesModuleIdLessonsCreateRoute,
  AuthenticatedCoursesCourseIdModulesModuleIdLessonsIndexRoute:
    AuthenticatedCoursesCourseIdModulesModuleIdLessonsIndexRoute,
  AuthenticatedCoursesCourseIdModulesModuleIdLessonsLessonIdEditRoute:
    AuthenticatedCoursesCourseIdModulesModuleIdLessonsLessonIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
