/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedWebinarsIndexRouteImport } from './routes/_authenticated/webinars/index'
import { Route as AuthenticatedVideoLessonsIndexRouteImport } from './routes/_authenticated/video-lessons/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSubjectsIndexRouteImport } from './routes/_authenticated/subjects/index'
import { Route as AuthenticatedSubjectClassIndexRouteImport } from './routes/_authenticated/subject-class/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSchoolsIndexRouteImport } from './routes/_authenticated/schools/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedClassesIndexRouteImport } from './routes/_authenticated/classes/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedWebinarsCreateRouteImport } from './routes/_authenticated/webinars/create'
import { Route as AuthenticatedWebinarsWebinarIdRouteImport } from './routes/_authenticated/webinars/$webinarId'
import { Route as AuthenticatedVideoLessonsCreateRouteImport } from './routes/_authenticated/video-lessons/create'
import { Route as AuthenticatedVideoLessonsVideoLessonIdRouteImport } from './routes/_authenticated/video-lessons/$videoLessonId'
import { Route as AuthenticatedUsersCreateRouteImport } from './routes/_authenticated/users/create'
import { Route as AuthenticatedSubjectsCreateRouteImport } from './routes/_authenticated/subjects/create'
import { Route as AuthenticatedSubjectClassCreateRouteImport } from './routes/_authenticated/subject-class/create'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSchoolsCreateRouteImport } from './routes/_authenticated/schools/create'
import { Route as AuthenticatedRolesCreateRouteImport } from './routes/_authenticated/roles/create'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedClassesCreateRouteImport } from './routes/_authenticated/classes/create'
import { Route as AuthenticatedDictionariesRegionsIndexRouteImport } from './routes/_authenticated/dictionaries/regions/index'
import { Route as AuthenticatedDictionariesDistrictsIndexRouteImport } from './routes/_authenticated/dictionaries/districts/index'
import { Route as AuthenticatedDictionariesCitiesIndexRouteImport } from './routes/_authenticated/dictionaries/cities/index'
import { Route as AuthenticatedWebinarsWebinarIdEditRouteImport } from './routes/_authenticated/webinars/$webinarId.edit'
import { Route as AuthenticatedVideoLessonsVideoLessonIdEditRouteImport } from './routes/_authenticated/video-lessons/$videoLessonId.edit'
import { Route as AuthenticatedUsersUserIdEditRouteImport } from './routes/_authenticated/users/$userId.edit'
import { Route as AuthenticatedSubjectsSubjectIdEditRouteImport } from './routes/_authenticated/subjects/$subjectId.edit'
import { Route as AuthenticatedSubjectClassSubjectClassIdEditRouteImport } from './routes/_authenticated/subject-class/$subjectClassId.edit'
import { Route as AuthenticatedSchoolsSchoolIdEditRouteImport } from './routes/_authenticated/schools/$schoolId.edit'
import { Route as AuthenticatedRolesRoleIdEditRouteImport } from './routes/_authenticated/roles/$roleId.edit'
import { Route as AuthenticatedDictionariesRegionsCreateRouteImport } from './routes/_authenticated/dictionaries/regions/create'
import { Route as AuthenticatedDictionariesDistrictsCreateRouteImport } from './routes/_authenticated/dictionaries/districts/create'
import { Route as AuthenticatedDictionariesCitiesCreateRouteImport } from './routes/_authenticated/dictionaries/cities/create'
import { Route as AuthenticatedClassesClassIdEditRouteImport } from './routes/_authenticated/classes/$classId.edit'
import { Route as AuthenticatedDictionariesRegionsDistrictIdEditRouteImport } from './routes/_authenticated/dictionaries/regions/$districtId.edit'
import { Route as AuthenticatedDictionariesDistrictsDistrictIdEditRouteImport } from './routes/_authenticated/dictionaries/districts/$districtId.edit'
import { Route as AuthenticatedDictionariesCitiesCityIdEditRouteImport } from './routes/_authenticated/dictionaries/cities/$cityId.edit'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebinarsIndexRoute =
  AuthenticatedWebinarsIndexRouteImport.update({
    id: '/webinars/',
    path: '/webinars/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVideoLessonsIndexRoute =
  AuthenticatedVideoLessonsIndexRouteImport.update({
    id: '/video-lessons/',
    path: '/video-lessons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubjectsIndexRoute =
  AuthenticatedSubjectsIndexRouteImport.update({
    id: '/subjects/',
    path: '/subjects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectClassIndexRoute =
  AuthenticatedSubjectClassIndexRouteImport.update({
    id: '/subject-class/',
    path: '/subject-class/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSchoolsIndexRoute =
  AuthenticatedSchoolsIndexRouteImport.update({
    id: '/schools/',
    path: '/schools/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesIndexRoute =
  AuthenticatedClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedWebinarsCreateRoute =
  AuthenticatedWebinarsCreateRouteImport.update({
    id: '/webinars/create',
    path: '/webinars/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebinarsWebinarIdRoute =
  AuthenticatedWebinarsWebinarIdRouteImport.update({
    id: '/webinars/$webinarId',
    path: '/webinars/$webinarId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVideoLessonsCreateRoute =
  AuthenticatedVideoLessonsCreateRouteImport.update({
    id: '/video-lessons/create',
    path: '/video-lessons/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVideoLessonsVideoLessonIdRoute =
  AuthenticatedVideoLessonsVideoLessonIdRouteImport.update({
    id: '/video-lessons/$videoLessonId',
    path: '/video-lessons/$videoLessonId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersCreateRoute =
  AuthenticatedUsersCreateRouteImport.update({
    id: '/users/create',
    path: '/users/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectsCreateRoute =
  AuthenticatedSubjectsCreateRouteImport.update({
    id: '/subjects/create',
    path: '/subjects/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectClassCreateRoute =
  AuthenticatedSubjectClassCreateRouteImport.update({
    id: '/subject-class/create',
    path: '/subject-class/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSchoolsCreateRoute =
  AuthenticatedSchoolsCreateRouteImport.update({
    id: '/schools/create',
    path: '/schools/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesCreateRoute =
  AuthenticatedRolesCreateRouteImport.update({
    id: '/roles/create',
    path: '/roles/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesCreateRoute =
  AuthenticatedClassesCreateRouteImport.update({
    id: '/classes/create',
    path: '/classes/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesRegionsIndexRoute =
  AuthenticatedDictionariesRegionsIndexRouteImport.update({
    id: '/dictionaries/regions/',
    path: '/dictionaries/regions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesDistrictsIndexRoute =
  AuthenticatedDictionariesDistrictsIndexRouteImport.update({
    id: '/dictionaries/districts/',
    path: '/dictionaries/districts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesCitiesIndexRoute =
  AuthenticatedDictionariesCitiesIndexRouteImport.update({
    id: '/dictionaries/cities/',
    path: '/dictionaries/cities/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebinarsWebinarIdEditRoute =
  AuthenticatedWebinarsWebinarIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedWebinarsWebinarIdRoute,
  } as any)
const AuthenticatedVideoLessonsVideoLessonIdEditRoute =
  AuthenticatedVideoLessonsVideoLessonIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedVideoLessonsVideoLessonIdRoute,
  } as any)
const AuthenticatedUsersUserIdEditRoute =
  AuthenticatedUsersUserIdEditRouteImport.update({
    id: '/users/$userId/edit',
    path: '/users/$userId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectsSubjectIdEditRoute =
  AuthenticatedSubjectsSubjectIdEditRouteImport.update({
    id: '/subjects/$subjectId/edit',
    path: '/subjects/$subjectId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubjectClassSubjectClassIdEditRoute =
  AuthenticatedSubjectClassSubjectClassIdEditRouteImport.update({
    id: '/subject-class/$subjectClassId/edit',
    path: '/subject-class/$subjectClassId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSchoolsSchoolIdEditRoute =
  AuthenticatedSchoolsSchoolIdEditRouteImport.update({
    id: '/schools/$schoolId/edit',
    path: '/schools/$schoolId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesRoleIdEditRoute =
  AuthenticatedRolesRoleIdEditRouteImport.update({
    id: '/roles/$roleId/edit',
    path: '/roles/$roleId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesRegionsCreateRoute =
  AuthenticatedDictionariesRegionsCreateRouteImport.update({
    id: '/dictionaries/regions/create',
    path: '/dictionaries/regions/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesDistrictsCreateRoute =
  AuthenticatedDictionariesDistrictsCreateRouteImport.update({
    id: '/dictionaries/districts/create',
    path: '/dictionaries/districts/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesCitiesCreateRoute =
  AuthenticatedDictionariesCitiesCreateRouteImport.update({
    id: '/dictionaries/cities/create',
    path: '/dictionaries/cities/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesClassIdEditRoute =
  AuthenticatedClassesClassIdEditRouteImport.update({
    id: '/classes/$classId/edit',
    path: '/classes/$classId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesRegionsDistrictIdEditRoute =
  AuthenticatedDictionariesRegionsDistrictIdEditRouteImport.update({
    id: '/dictionaries/regions/$districtId/edit',
    path: '/dictionaries/regions/$districtId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesDistrictsDistrictIdEditRoute =
  AuthenticatedDictionariesDistrictsDistrictIdEditRouteImport.update({
    id: '/dictionaries/districts/$districtId/edit',
    path: '/dictionaries/districts/$districtId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDictionariesCitiesCityIdEditRoute =
  AuthenticatedDictionariesCitiesCityIdEditRouteImport.update({
    id: '/dictionaries/cities/$cityId/edit',
    path: '/dictionaries/cities/$cityId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/classes/create': typeof AuthenticatedClassesCreateRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/roles/create': typeof AuthenticatedRolesCreateRoute
  '/schools/create': typeof AuthenticatedSchoolsCreateRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/subject-class/create': typeof AuthenticatedSubjectClassCreateRoute
  '/subjects/create': typeof AuthenticatedSubjectsCreateRoute
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/video-lessons/$videoLessonId': typeof AuthenticatedVideoLessonsVideoLessonIdRouteWithChildren
  '/video-lessons/create': typeof AuthenticatedVideoLessonsCreateRoute
  '/webinars/$webinarId': typeof AuthenticatedWebinarsWebinarIdRouteWithChildren
  '/webinars/create': typeof AuthenticatedWebinarsCreateRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/schools': typeof AuthenticatedSchoolsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/subject-class': typeof AuthenticatedSubjectClassIndexRoute
  '/subjects': typeof AuthenticatedSubjectsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/video-lessons': typeof AuthenticatedVideoLessonsIndexRoute
  '/webinars': typeof AuthenticatedWebinarsIndexRoute
  '/classes/$classId/edit': typeof AuthenticatedClassesClassIdEditRoute
  '/dictionaries/cities/create': typeof AuthenticatedDictionariesCitiesCreateRoute
  '/dictionaries/districts/create': typeof AuthenticatedDictionariesDistrictsCreateRoute
  '/dictionaries/regions/create': typeof AuthenticatedDictionariesRegionsCreateRoute
  '/roles/$roleId/edit': typeof AuthenticatedRolesRoleIdEditRoute
  '/schools/$schoolId/edit': typeof AuthenticatedSchoolsSchoolIdEditRoute
  '/subject-class/$subjectClassId/edit': typeof AuthenticatedSubjectClassSubjectClassIdEditRoute
  '/subjects/$subjectId/edit': typeof AuthenticatedSubjectsSubjectIdEditRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/video-lessons/$videoLessonId/edit': typeof AuthenticatedVideoLessonsVideoLessonIdEditRoute
  '/webinars/$webinarId/edit': typeof AuthenticatedWebinarsWebinarIdEditRoute
  '/dictionaries/cities': typeof AuthenticatedDictionariesCitiesIndexRoute
  '/dictionaries/districts': typeof AuthenticatedDictionariesDistrictsIndexRoute
  '/dictionaries/regions': typeof AuthenticatedDictionariesRegionsIndexRoute
  '/dictionaries/cities/$cityId/edit': typeof AuthenticatedDictionariesCitiesCityIdEditRoute
  '/dictionaries/districts/$districtId/edit': typeof AuthenticatedDictionariesDistrictsDistrictIdEditRoute
  '/dictionaries/regions/$districtId/edit': typeof AuthenticatedDictionariesRegionsDistrictIdEditRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/classes/create': typeof AuthenticatedClassesCreateRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/roles/create': typeof AuthenticatedRolesCreateRoute
  '/schools/create': typeof AuthenticatedSchoolsCreateRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/subject-class/create': typeof AuthenticatedSubjectClassCreateRoute
  '/subjects/create': typeof AuthenticatedSubjectsCreateRoute
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/video-lessons/$videoLessonId': typeof AuthenticatedVideoLessonsVideoLessonIdRouteWithChildren
  '/video-lessons/create': typeof AuthenticatedVideoLessonsCreateRoute
  '/webinars/$webinarId': typeof AuthenticatedWebinarsWebinarIdRouteWithChildren
  '/webinars/create': typeof AuthenticatedWebinarsCreateRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/schools': typeof AuthenticatedSchoolsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/subject-class': typeof AuthenticatedSubjectClassIndexRoute
  '/subjects': typeof AuthenticatedSubjectsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/video-lessons': typeof AuthenticatedVideoLessonsIndexRoute
  '/webinars': typeof AuthenticatedWebinarsIndexRoute
  '/classes/$classId/edit': typeof AuthenticatedClassesClassIdEditRoute
  '/dictionaries/cities/create': typeof AuthenticatedDictionariesCitiesCreateRoute
  '/dictionaries/districts/create': typeof AuthenticatedDictionariesDistrictsCreateRoute
  '/dictionaries/regions/create': typeof AuthenticatedDictionariesRegionsCreateRoute
  '/roles/$roleId/edit': typeof AuthenticatedRolesRoleIdEditRoute
  '/schools/$schoolId/edit': typeof AuthenticatedSchoolsSchoolIdEditRoute
  '/subject-class/$subjectClassId/edit': typeof AuthenticatedSubjectClassSubjectClassIdEditRoute
  '/subjects/$subjectId/edit': typeof AuthenticatedSubjectsSubjectIdEditRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/video-lessons/$videoLessonId/edit': typeof AuthenticatedVideoLessonsVideoLessonIdEditRoute
  '/webinars/$webinarId/edit': typeof AuthenticatedWebinarsWebinarIdEditRoute
  '/dictionaries/cities': typeof AuthenticatedDictionariesCitiesIndexRoute
  '/dictionaries/districts': typeof AuthenticatedDictionariesDistrictsIndexRoute
  '/dictionaries/regions': typeof AuthenticatedDictionariesRegionsIndexRoute
  '/dictionaries/cities/$cityId/edit': typeof AuthenticatedDictionariesCitiesCityIdEditRoute
  '/dictionaries/districts/$districtId/edit': typeof AuthenticatedDictionariesDistrictsDistrictIdEditRoute
  '/dictionaries/regions/$districtId/edit': typeof AuthenticatedDictionariesRegionsDistrictIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/classes/create': typeof AuthenticatedClassesCreateRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/roles/create': typeof AuthenticatedRolesCreateRoute
  '/_authenticated/schools/create': typeof AuthenticatedSchoolsCreateRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/subject-class/create': typeof AuthenticatedSubjectClassCreateRoute
  '/_authenticated/subjects/create': typeof AuthenticatedSubjectsCreateRoute
  '/_authenticated/users/create': typeof AuthenticatedUsersCreateRoute
  '/_authenticated/video-lessons/$videoLessonId': typeof AuthenticatedVideoLessonsVideoLessonIdRouteWithChildren
  '/_authenticated/video-lessons/create': typeof AuthenticatedVideoLessonsCreateRoute
  '/_authenticated/webinars/$webinarId': typeof AuthenticatedWebinarsWebinarIdRouteWithChildren
  '/_authenticated/webinars/create': typeof AuthenticatedWebinarsCreateRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/classes/': typeof AuthenticatedClassesIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/schools/': typeof AuthenticatedSchoolsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/subject-class/': typeof AuthenticatedSubjectClassIndexRoute
  '/_authenticated/subjects/': typeof AuthenticatedSubjectsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/video-lessons/': typeof AuthenticatedVideoLessonsIndexRoute
  '/_authenticated/webinars/': typeof AuthenticatedWebinarsIndexRoute
  '/_authenticated/classes/$classId/edit': typeof AuthenticatedClassesClassIdEditRoute
  '/_authenticated/dictionaries/cities/create': typeof AuthenticatedDictionariesCitiesCreateRoute
  '/_authenticated/dictionaries/districts/create': typeof AuthenticatedDictionariesDistrictsCreateRoute
  '/_authenticated/dictionaries/regions/create': typeof AuthenticatedDictionariesRegionsCreateRoute
  '/_authenticated/roles/$roleId/edit': typeof AuthenticatedRolesRoleIdEditRoute
  '/_authenticated/schools/$schoolId/edit': typeof AuthenticatedSchoolsSchoolIdEditRoute
  '/_authenticated/subject-class/$subjectClassId/edit': typeof AuthenticatedSubjectClassSubjectClassIdEditRoute
  '/_authenticated/subjects/$subjectId/edit': typeof AuthenticatedSubjectsSubjectIdEditRoute
  '/_authenticated/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/_authenticated/video-lessons/$videoLessonId/edit': typeof AuthenticatedVideoLessonsVideoLessonIdEditRoute
  '/_authenticated/webinars/$webinarId/edit': typeof AuthenticatedWebinarsWebinarIdEditRoute
  '/_authenticated/dictionaries/cities/': typeof AuthenticatedDictionariesCitiesIndexRoute
  '/_authenticated/dictionaries/districts/': typeof AuthenticatedDictionariesDistrictsIndexRoute
  '/_authenticated/dictionaries/regions/': typeof AuthenticatedDictionariesRegionsIndexRoute
  '/_authenticated/dictionaries/cities/$cityId/edit': typeof AuthenticatedDictionariesCitiesCityIdEditRoute
  '/_authenticated/dictionaries/districts/$districtId/edit': typeof AuthenticatedDictionariesDistrictsDistrictIdEditRoute
  '/_authenticated/dictionaries/regions/$districtId/edit': typeof AuthenticatedDictionariesRegionsDistrictIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/classes/create'
    | '/errors/$error'
    | '/roles/create'
    | '/schools/create'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/subject-class/create'
    | '/subjects/create'
    | '/users/create'
    | '/video-lessons/$videoLessonId'
    | '/video-lessons/create'
    | '/webinars/$webinarId'
    | '/webinars/create'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/classes'
    | '/help-center'
    | '/roles'
    | '/schools'
    | '/settings/'
    | '/subject-class'
    | '/subjects'
    | '/tasks'
    | '/users'
    | '/video-lessons'
    | '/webinars'
    | '/classes/$classId/edit'
    | '/dictionaries/cities/create'
    | '/dictionaries/districts/create'
    | '/dictionaries/regions/create'
    | '/roles/$roleId/edit'
    | '/schools/$schoolId/edit'
    | '/subject-class/$subjectClassId/edit'
    | '/subjects/$subjectId/edit'
    | '/users/$userId/edit'
    | '/video-lessons/$videoLessonId/edit'
    | '/webinars/$webinarId/edit'
    | '/dictionaries/cities'
    | '/dictionaries/districts'
    | '/dictionaries/regions'
    | '/dictionaries/cities/$cityId/edit'
    | '/dictionaries/districts/$districtId/edit'
    | '/dictionaries/regions/$districtId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/classes/create'
    | '/errors/$error'
    | '/roles/create'
    | '/schools/create'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/subject-class/create'
    | '/subjects/create'
    | '/users/create'
    | '/video-lessons/$videoLessonId'
    | '/video-lessons/create'
    | '/webinars/$webinarId'
    | '/webinars/create'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/chats'
    | '/classes'
    | '/help-center'
    | '/roles'
    | '/schools'
    | '/settings'
    | '/subject-class'
    | '/subjects'
    | '/tasks'
    | '/users'
    | '/video-lessons'
    | '/webinars'
    | '/classes/$classId/edit'
    | '/dictionaries/cities/create'
    | '/dictionaries/districts/create'
    | '/dictionaries/regions/create'
    | '/roles/$roleId/edit'
    | '/schools/$schoolId/edit'
    | '/subject-class/$subjectClassId/edit'
    | '/subjects/$subjectId/edit'
    | '/users/$userId/edit'
    | '/video-lessons/$videoLessonId/edit'
    | '/webinars/$webinarId/edit'
    | '/dictionaries/cities'
    | '/dictionaries/districts'
    | '/dictionaries/regions'
    | '/dictionaries/cities/$cityId/edit'
    | '/dictionaries/districts/$districtId/edit'
    | '/dictionaries/regions/$districtId/edit'
  id:
    | '__root__'
    | '/(auth)'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/classes/create'
    | '/_authenticated/errors/$error'
    | '/_authenticated/roles/create'
    | '/_authenticated/schools/create'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/subject-class/create'
    | '/_authenticated/subjects/create'
    | '/_authenticated/users/create'
    | '/_authenticated/video-lessons/$videoLessonId'
    | '/_authenticated/video-lessons/create'
    | '/_authenticated/webinars/$webinarId'
    | '/_authenticated/webinars/create'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/classes/'
    | '/_authenticated/help-center/'
    | '/_authenticated/roles/'
    | '/_authenticated/schools/'
    | '/_authenticated/settings/'
    | '/_authenticated/subject-class/'
    | '/_authenticated/subjects/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/video-lessons/'
    | '/_authenticated/webinars/'
    | '/_authenticated/classes/$classId/edit'
    | '/_authenticated/dictionaries/cities/create'
    | '/_authenticated/dictionaries/districts/create'
    | '/_authenticated/dictionaries/regions/create'
    | '/_authenticated/roles/$roleId/edit'
    | '/_authenticated/schools/$schoolId/edit'
    | '/_authenticated/subject-class/$subjectClassId/edit'
    | '/_authenticated/subjects/$subjectId/edit'
    | '/_authenticated/users/$userId/edit'
    | '/_authenticated/video-lessons/$videoLessonId/edit'
    | '/_authenticated/webinars/$webinarId/edit'
    | '/_authenticated/dictionaries/cities/'
    | '/_authenticated/dictionaries/districts/'
    | '/_authenticated/dictionaries/regions/'
    | '/_authenticated/dictionaries/cities/$cityId/edit'
    | '/_authenticated/dictionaries/districts/$districtId/edit'
    | '/_authenticated/dictionaries/regions/$districtId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webinars/': {
      id: '/_authenticated/webinars/'
      path: '/webinars'
      fullPath: '/webinars'
      preLoaderRoute: typeof AuthenticatedWebinarsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/video-lessons/': {
      id: '/_authenticated/video-lessons/'
      path: '/video-lessons'
      fullPath: '/video-lessons'
      preLoaderRoute: typeof AuthenticatedVideoLessonsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/': {
      id: '/_authenticated/subjects/'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AuthenticatedSubjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subject-class/': {
      id: '/_authenticated/subject-class/'
      path: '/subject-class'
      fullPath: '/subject-class'
      preLoaderRoute: typeof AuthenticatedSubjectClassIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/schools/': {
      id: '/_authenticated/schools/'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof AuthenticatedSchoolsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/': {
      id: '/_authenticated/classes/'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/webinars/create': {
      id: '/_authenticated/webinars/create'
      path: '/webinars/create'
      fullPath: '/webinars/create'
      preLoaderRoute: typeof AuthenticatedWebinarsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webinars/$webinarId': {
      id: '/_authenticated/webinars/$webinarId'
      path: '/webinars/$webinarId'
      fullPath: '/webinars/$webinarId'
      preLoaderRoute: typeof AuthenticatedWebinarsWebinarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/video-lessons/create': {
      id: '/_authenticated/video-lessons/create'
      path: '/video-lessons/create'
      fullPath: '/video-lessons/create'
      preLoaderRoute: typeof AuthenticatedVideoLessonsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/video-lessons/$videoLessonId': {
      id: '/_authenticated/video-lessons/$videoLessonId'
      path: '/video-lessons/$videoLessonId'
      fullPath: '/video-lessons/$videoLessonId'
      preLoaderRoute: typeof AuthenticatedVideoLessonsVideoLessonIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/create': {
      id: '/_authenticated/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AuthenticatedUsersCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/create': {
      id: '/_authenticated/subjects/create'
      path: '/subjects/create'
      fullPath: '/subjects/create'
      preLoaderRoute: typeof AuthenticatedSubjectsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subject-class/create': {
      id: '/_authenticated/subject-class/create'
      path: '/subject-class/create'
      fullPath: '/subject-class/create'
      preLoaderRoute: typeof AuthenticatedSubjectClassCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/schools/create': {
      id: '/_authenticated/schools/create'
      path: '/schools/create'
      fullPath: '/schools/create'
      preLoaderRoute: typeof AuthenticatedSchoolsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/create': {
      id: '/_authenticated/roles/create'
      path: '/roles/create'
      fullPath: '/roles/create'
      preLoaderRoute: typeof AuthenticatedRolesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/create': {
      id: '/_authenticated/classes/create'
      path: '/classes/create'
      fullPath: '/classes/create'
      preLoaderRoute: typeof AuthenticatedClassesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/regions/': {
      id: '/_authenticated/dictionaries/regions/'
      path: '/dictionaries/regions'
      fullPath: '/dictionaries/regions'
      preLoaderRoute: typeof AuthenticatedDictionariesRegionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/districts/': {
      id: '/_authenticated/dictionaries/districts/'
      path: '/dictionaries/districts'
      fullPath: '/dictionaries/districts'
      preLoaderRoute: typeof AuthenticatedDictionariesDistrictsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/cities/': {
      id: '/_authenticated/dictionaries/cities/'
      path: '/dictionaries/cities'
      fullPath: '/dictionaries/cities'
      preLoaderRoute: typeof AuthenticatedDictionariesCitiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/webinars/$webinarId/edit': {
      id: '/_authenticated/webinars/$webinarId/edit'
      path: '/edit'
      fullPath: '/webinars/$webinarId/edit'
      preLoaderRoute: typeof AuthenticatedWebinarsWebinarIdEditRouteImport
      parentRoute: typeof AuthenticatedWebinarsWebinarIdRoute
    }
    '/_authenticated/video-lessons/$videoLessonId/edit': {
      id: '/_authenticated/video-lessons/$videoLessonId/edit'
      path: '/edit'
      fullPath: '/video-lessons/$videoLessonId/edit'
      preLoaderRoute: typeof AuthenticatedVideoLessonsVideoLessonIdEditRouteImport
      parentRoute: typeof AuthenticatedVideoLessonsVideoLessonIdRoute
    }
    '/_authenticated/users/$userId/edit': {
      id: '/_authenticated/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof AuthenticatedUsersUserIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subjects/$subjectId/edit': {
      id: '/_authenticated/subjects/$subjectId/edit'
      path: '/subjects/$subjectId/edit'
      fullPath: '/subjects/$subjectId/edit'
      preLoaderRoute: typeof AuthenticatedSubjectsSubjectIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subject-class/$subjectClassId/edit': {
      id: '/_authenticated/subject-class/$subjectClassId/edit'
      path: '/subject-class/$subjectClassId/edit'
      fullPath: '/subject-class/$subjectClassId/edit'
      preLoaderRoute: typeof AuthenticatedSubjectClassSubjectClassIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schools/$schoolId/edit': {
      id: '/_authenticated/schools/$schoolId/edit'
      path: '/schools/$schoolId/edit'
      fullPath: '/schools/$schoolId/edit'
      preLoaderRoute: typeof AuthenticatedSchoolsSchoolIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles/$roleId/edit': {
      id: '/_authenticated/roles/$roleId/edit'
      path: '/roles/$roleId/edit'
      fullPath: '/roles/$roleId/edit'
      preLoaderRoute: typeof AuthenticatedRolesRoleIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/regions/create': {
      id: '/_authenticated/dictionaries/regions/create'
      path: '/dictionaries/regions/create'
      fullPath: '/dictionaries/regions/create'
      preLoaderRoute: typeof AuthenticatedDictionariesRegionsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/districts/create': {
      id: '/_authenticated/dictionaries/districts/create'
      path: '/dictionaries/districts/create'
      fullPath: '/dictionaries/districts/create'
      preLoaderRoute: typeof AuthenticatedDictionariesDistrictsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/cities/create': {
      id: '/_authenticated/dictionaries/cities/create'
      path: '/dictionaries/cities/create'
      fullPath: '/dictionaries/cities/create'
      preLoaderRoute: typeof AuthenticatedDictionariesCitiesCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes/$classId/edit': {
      id: '/_authenticated/classes/$classId/edit'
      path: '/classes/$classId/edit'
      fullPath: '/classes/$classId/edit'
      preLoaderRoute: typeof AuthenticatedClassesClassIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/regions/$districtId/edit': {
      id: '/_authenticated/dictionaries/regions/$districtId/edit'
      path: '/dictionaries/regions/$districtId/edit'
      fullPath: '/dictionaries/regions/$districtId/edit'
      preLoaderRoute: typeof AuthenticatedDictionariesRegionsDistrictIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/districts/$districtId/edit': {
      id: '/_authenticated/dictionaries/districts/$districtId/edit'
      path: '/dictionaries/districts/$districtId/edit'
      fullPath: '/dictionaries/districts/$districtId/edit'
      preLoaderRoute: typeof AuthenticatedDictionariesDistrictsDistrictIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dictionaries/cities/$cityId/edit': {
      id: '/_authenticated/dictionaries/cities/$cityId/edit'
      path: '/dictionaries/cities/$cityId/edit'
      fullPath: '/dictionaries/cities/$cityId/edit'
      preLoaderRoute: typeof AuthenticatedDictionariesCitiesCityIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedVideoLessonsVideoLessonIdRouteChildren {
  AuthenticatedVideoLessonsVideoLessonIdEditRoute: typeof AuthenticatedVideoLessonsVideoLessonIdEditRoute
}

const AuthenticatedVideoLessonsVideoLessonIdRouteChildren: AuthenticatedVideoLessonsVideoLessonIdRouteChildren =
  {
    AuthenticatedVideoLessonsVideoLessonIdEditRoute:
      AuthenticatedVideoLessonsVideoLessonIdEditRoute,
  }

const AuthenticatedVideoLessonsVideoLessonIdRouteWithChildren =
  AuthenticatedVideoLessonsVideoLessonIdRoute._addFileChildren(
    AuthenticatedVideoLessonsVideoLessonIdRouteChildren,
  )

interface AuthenticatedWebinarsWebinarIdRouteChildren {
  AuthenticatedWebinarsWebinarIdEditRoute: typeof AuthenticatedWebinarsWebinarIdEditRoute
}

const AuthenticatedWebinarsWebinarIdRouteChildren: AuthenticatedWebinarsWebinarIdRouteChildren =
  {
    AuthenticatedWebinarsWebinarIdEditRoute:
      AuthenticatedWebinarsWebinarIdEditRoute,
  }

const AuthenticatedWebinarsWebinarIdRouteWithChildren =
  AuthenticatedWebinarsWebinarIdRoute._addFileChildren(
    AuthenticatedWebinarsWebinarIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClassesCreateRoute: typeof AuthenticatedClassesCreateRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedRolesCreateRoute: typeof AuthenticatedRolesCreateRoute
  AuthenticatedSchoolsCreateRoute: typeof AuthenticatedSchoolsCreateRoute
  AuthenticatedSubjectClassCreateRoute: typeof AuthenticatedSubjectClassCreateRoute
  AuthenticatedSubjectsCreateRoute: typeof AuthenticatedSubjectsCreateRoute
  AuthenticatedUsersCreateRoute: typeof AuthenticatedUsersCreateRoute
  AuthenticatedVideoLessonsVideoLessonIdRoute: typeof AuthenticatedVideoLessonsVideoLessonIdRouteWithChildren
  AuthenticatedVideoLessonsCreateRoute: typeof AuthenticatedVideoLessonsCreateRoute
  AuthenticatedWebinarsWebinarIdRoute: typeof AuthenticatedWebinarsWebinarIdRouteWithChildren
  AuthenticatedWebinarsCreateRoute: typeof AuthenticatedWebinarsCreateRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedClassesIndexRoute: typeof AuthenticatedClassesIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedSchoolsIndexRoute: typeof AuthenticatedSchoolsIndexRoute
  AuthenticatedSubjectClassIndexRoute: typeof AuthenticatedSubjectClassIndexRoute
  AuthenticatedSubjectsIndexRoute: typeof AuthenticatedSubjectsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedVideoLessonsIndexRoute: typeof AuthenticatedVideoLessonsIndexRoute
  AuthenticatedWebinarsIndexRoute: typeof AuthenticatedWebinarsIndexRoute
  AuthenticatedClassesClassIdEditRoute: typeof AuthenticatedClassesClassIdEditRoute
  AuthenticatedDictionariesCitiesCreateRoute: typeof AuthenticatedDictionariesCitiesCreateRoute
  AuthenticatedDictionariesDistrictsCreateRoute: typeof AuthenticatedDictionariesDistrictsCreateRoute
  AuthenticatedDictionariesRegionsCreateRoute: typeof AuthenticatedDictionariesRegionsCreateRoute
  AuthenticatedRolesRoleIdEditRoute: typeof AuthenticatedRolesRoleIdEditRoute
  AuthenticatedSchoolsSchoolIdEditRoute: typeof AuthenticatedSchoolsSchoolIdEditRoute
  AuthenticatedSubjectClassSubjectClassIdEditRoute: typeof AuthenticatedSubjectClassSubjectClassIdEditRoute
  AuthenticatedSubjectsSubjectIdEditRoute: typeof AuthenticatedSubjectsSubjectIdEditRoute
  AuthenticatedUsersUserIdEditRoute: typeof AuthenticatedUsersUserIdEditRoute
  AuthenticatedDictionariesCitiesIndexRoute: typeof AuthenticatedDictionariesCitiesIndexRoute
  AuthenticatedDictionariesDistrictsIndexRoute: typeof AuthenticatedDictionariesDistrictsIndexRoute
  AuthenticatedDictionariesRegionsIndexRoute: typeof AuthenticatedDictionariesRegionsIndexRoute
  AuthenticatedDictionariesCitiesCityIdEditRoute: typeof AuthenticatedDictionariesCitiesCityIdEditRoute
  AuthenticatedDictionariesDistrictsDistrictIdEditRoute: typeof AuthenticatedDictionariesDistrictsDistrictIdEditRoute
  AuthenticatedDictionariesRegionsDistrictIdEditRoute: typeof AuthenticatedDictionariesRegionsDistrictIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClassesCreateRoute: AuthenticatedClassesCreateRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedRolesCreateRoute: AuthenticatedRolesCreateRoute,
  AuthenticatedSchoolsCreateRoute: AuthenticatedSchoolsCreateRoute,
  AuthenticatedSubjectClassCreateRoute: AuthenticatedSubjectClassCreateRoute,
  AuthenticatedSubjectsCreateRoute: AuthenticatedSubjectsCreateRoute,
  AuthenticatedUsersCreateRoute: AuthenticatedUsersCreateRoute,
  AuthenticatedVideoLessonsVideoLessonIdRoute:
    AuthenticatedVideoLessonsVideoLessonIdRouteWithChildren,
  AuthenticatedVideoLessonsCreateRoute: AuthenticatedVideoLessonsCreateRoute,
  AuthenticatedWebinarsWebinarIdRoute:
    AuthenticatedWebinarsWebinarIdRouteWithChildren,
  AuthenticatedWebinarsCreateRoute: AuthenticatedWebinarsCreateRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedClassesIndexRoute: AuthenticatedClassesIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedSchoolsIndexRoute: AuthenticatedSchoolsIndexRoute,
  AuthenticatedSubjectClassIndexRoute: AuthenticatedSubjectClassIndexRoute,
  AuthenticatedSubjectsIndexRoute: AuthenticatedSubjectsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedVideoLessonsIndexRoute: AuthenticatedVideoLessonsIndexRoute,
  AuthenticatedWebinarsIndexRoute: AuthenticatedWebinarsIndexRoute,
  AuthenticatedClassesClassIdEditRoute: AuthenticatedClassesClassIdEditRoute,
  AuthenticatedDictionariesCitiesCreateRoute:
    AuthenticatedDictionariesCitiesCreateRoute,
  AuthenticatedDictionariesDistrictsCreateRoute:
    AuthenticatedDictionariesDistrictsCreateRoute,
  AuthenticatedDictionariesRegionsCreateRoute:
    AuthenticatedDictionariesRegionsCreateRoute,
  AuthenticatedRolesRoleIdEditRoute: AuthenticatedRolesRoleIdEditRoute,
  AuthenticatedSchoolsSchoolIdEditRoute: AuthenticatedSchoolsSchoolIdEditRoute,
  AuthenticatedSubjectClassSubjectClassIdEditRoute:
    AuthenticatedSubjectClassSubjectClassIdEditRoute,
  AuthenticatedSubjectsSubjectIdEditRoute:
    AuthenticatedSubjectsSubjectIdEditRoute,
  AuthenticatedUsersUserIdEditRoute: AuthenticatedUsersUserIdEditRoute,
  AuthenticatedDictionariesCitiesIndexRoute:
    AuthenticatedDictionariesCitiesIndexRoute,
  AuthenticatedDictionariesDistrictsIndexRoute:
    AuthenticatedDictionariesDistrictsIndexRoute,
  AuthenticatedDictionariesRegionsIndexRoute:
    AuthenticatedDictionariesRegionsIndexRoute,
  AuthenticatedDictionariesCitiesCityIdEditRoute:
    AuthenticatedDictionariesCitiesCityIdEditRoute,
  AuthenticatedDictionariesDistrictsDistrictIdEditRoute:
    AuthenticatedDictionariesDistrictsDistrictIdEditRoute,
  AuthenticatedDictionariesRegionsDistrictIdEditRoute:
    AuthenticatedDictionariesRegionsDistrictIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
